//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public long MaHD { get; set; }
        public long MaTK { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<long> MaThe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<long> TongTien { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string SDTKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ThanhToanOnline ThanhToanOnline { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
    }
}
