//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCMT
    {
        public long MaRep { get; set; }
        public long MaCMT { get; set; }
        public long MaTK { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
